/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marcelo
 */
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class cuenta extends javax.swing.JFrame {

    /**
     * Creates new form cuenta
     */
    public cuenta() {
        initComponents();
    }
int maxclientes=5;
int maxcuentas=5;
int maxtransacciones=100;
int contclientes=-1;
int contcuentas=1;
int conttransacciones=-1;
String[][] tablaclientes = new String[maxclientes][3];
int[][] tablacuentas = new int[maxclientes][maxcuentas];
int[] tablacuentasclientes = new int [maxclientes*maxcuentas];
String[][] tabltransaccioness = new String[maxtransacciones][2];
double[][] tablatransaccionesi = new double [maxtransacciones][4];
double[] tablasaldos = new double[maxclientes*maxcuentas];

    //int[] Asaldo = new int[MAXproducto-1];
        

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btcuenta = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfcui = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfapellido = new javax.swing.JTextField();
        btcliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cbcliente = new javax.swing.JComboBox<>();
        btcuentas = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuadroclientes = new javax.swing.JTable();
        btbuscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        cuadrocuentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cborigen = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cbdestino = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        txtransferencias = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbservicios = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        cbtipo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        txservicios = new javax.swing.JTextField();
        btservicios = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        repcui = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        repnombre = new javax.swing.JTextField();
        repapellido = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        repcuadro = new javax.swing.JTable();
        btreporte = new javax.swing.JButton();
        repcuenta = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cbdepositos = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txdepositos = new javax.swing.JTextField();
        btdepositos = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btcuenta.setName(""); // NOI18N

        jLabel1.setText("CUI");

        tfcui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcuiActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        btcliente.setText("Crear");
        btcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(btcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(238, 238, 238))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfcui)
                    .addComponent(tfnombre)
                    .addComponent(tfapellido)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(tfcui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(tfapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        btcuenta.addTab("Regitar Cliente", jPanel1);

        jLabel4.setText("Crear Cuenta");

        cbcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbclienteActionPerformed(evt);
            }
        });

        btcuentas.setText("Crear");
        btcuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcuentasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(cbcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(227, 227, 227)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(245, 245, 245)
                                .addComponent(btcuentas)))
                        .addGap(0, 218, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(cbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 241, Short.MAX_VALUE)
                .addComponent(btcuentas)
                .addGap(39, 39, 39))
        );

        btcuenta.addTab("Crear Cuenta", jPanel4);

        cuadroclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cuadroclientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        cuadroclientes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cuadroclientesFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(cuadroclientes);

        btbuscar.setText("Buscar Cuentas Asociadas");
        btbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbuscarActionPerformed(evt);
            }
        });

        cuadrocuentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        cuadrocuentas.setEditingRow(0);
        jScrollPane3.setViewportView(cuadrocuentas);

        jLabel5.setText("Seleccione una cuenta");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(btbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btbuscar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btcuenta.addTab("Ver Clientes", jPanel5);

        jLabel8.setText("Cuenta de origen");

        jLabel9.setText("Cuenta de destino");

        jLabel10.setText("Monto");

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 207, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(txtransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(234, 234, 234))))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cborigen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbdestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(220, 220, 220))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(256, 256, 256))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(220, 220, 220))))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(cborigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(cbdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtransferencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addGap(7, 7, 7))
        );

        btcuenta.addTab("Transferencias", jPanel7);

        jLabel11.setText("Cuenta a debitar");

        jLabel12.setText("Tipo de servicio");

        cbtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Luz", "Agua", "Teléfono" }));

        jLabel13.setText("Monto");

        btservicios.setText("Acptar");
        btservicios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btserviciosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbservicios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(241, 241, 241)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txservicios)
                                    .addComponent(btservicios, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(258, 258, 258)
                                .addComponent(jLabel13))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(233, 233, 233)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addComponent(jLabel11)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(cbservicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(cbtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txservicios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btservicios)
                .addGap(6, 6, 6))
        );

        btcuenta.addTab("Pago de sevicios", jPanel8);

        jLabel14.setText("ID Cuenta");

        jLabel15.setText("CUI");

        jLabel16.setText("Nombre");

        jLabel17.setText("Apellido");

        repcuadro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(repcuadro);

        btreporte.setText("Mostar transacciones");
        btreporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(repcui)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(repcuenta))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(repnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(repapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btreporte))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btreporte)
                    .addComponent(repcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(repcui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        btcuenta.addTab("Historial", jPanel9);

        jLabel6.setText("Cuenta");

        cbdepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdepositosActionPerformed(evt);
            }
        });

        jLabel7.setText("Monto");

        btdepositos.setText("Aceptar");
        btdepositos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdepositosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(cbdepositos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(259, 259, 259))))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(txdepositos, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btdepositos)
                        .addGap(239, 239, 239))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(257, 257, 257))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(cbdepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(txdepositos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btdepositos)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        btcuenta.addTab("Depositos", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btcuenta)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btcuenta)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
//    public int buscarcui (String cui){
//        int encontrado=-1;
//        for (int temp=0; temp<=contclientes; temp++) {
//            if (cui.equals(tablaclientes[temp][0])) {
//                encontrado=temp;
//            }
//        }
//        return encontrado;    
//    }
        
    private void btclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclienteActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CUI");
        model.addColumn("Nombre");
        model.addColumn("Apellido");
        
        String varcliente="";
        if (contclientes<maxclientes-1) { 
          if (tfcui.getText().length()>0 && tfnombre.getText().length()>0 && tfapellido.getText().length()>0) {
            int encontrado=-1;
            for (int temp=0; temp<=contclientes; temp++) {
                if (tfcui.getText().equals(tablaclientes[temp][0])) {
                encontrado=temp;
              }
            }
            if (encontrado<0) {
              contclientes=contclientes+1;
              tablaclientes[contclientes][0]=tfcui.getText();
              tablaclientes[contclientes][1]=tfnombre.getText();
              tablaclientes[contclientes][2]=tfapellido.getText();
              
              System.out.println(contclientes);
              varcliente=tablaclientes[contclientes][0]+" - "+tablaclientes[contclientes][1]+" "+tablaclientes[contclientes][2];
              System.out.println(varcliente);
              
              // Agregamos cliente al combo box de clientes
              cbcliente.addItem(varcliente);
              
              // Agregamos cliente al cuadro de clientes
              //model.addRow(new Object[]{tablaclientes[contclientes][0],tablaclientes[contclientes][1],tablaclientes[contclientes][2]});
              //cuadroclientes.setModel(model); 
              
              
            
              }
              else {
                JOptionPane.showMessageDialog(null, "El CUI ya existe");
              }
          }  
          else {
            JOptionPane.showMessageDialog(null, "Los campos deben tener valores");
          }
        }
        else {
          JOptionPane.showMessageDialog(null, "no es posible crear mas clientes");
        }
        
        if (contclientes>=0)   {
            for(int temp=0; temp<=contclientes; temp++) {
                model.addRow(new Object[]{tablaclientes[temp][0],tablaclientes[temp][1],tablaclientes[temp][2]});  
                cuadroclientes.setModel(model); 
            }  
        }
        
        
        
    }//GEN-LAST:event_btclienteActionPerformed

    private void btcuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcuentasActionPerformed
        // TODO add your handling code here:
        int opcion = cbcliente.getSelectedIndex();    
        int poscuenta = -1;
        int temp =0;

        while (temp<maxcuentas) {
            if (tablacuentas[opcion][temp]>0) {
                temp=temp+1;
            }
            else {
                poscuenta=temp;
                temp=maxcuentas;
            }
        }    
        if (poscuenta>=0) {
            tablacuentas[opcion][poscuenta]=contcuentas;
            tablacuentasclientes[contcuentas]=opcion;
            cbdepositos.addItem(contcuentas+" cuenta de "+tablaclientes[opcion][1]+" "+tablaclientes[opcion][2]);
            cbservicios.addItem(contcuentas+" cuenta de "+tablaclientes[opcion][1]+" "+tablaclientes[opcion][2]);
            cborigen.addItem(contcuentas+" cuenta de "+tablaclientes[opcion][1]+" "+tablaclientes[opcion][2]);
            cbdestino.addItem(contcuentas+" cuenta de "+tablaclientes[opcion][1]+" "+tablaclientes[opcion][2]);
            System.out.println("Cuenta: "+contcuentas+" en: "+opcion+","+poscuenta);
            contcuentas=contcuentas+1;
                     
        }
        else {
            JOptionPane.showMessageDialog(null, "Este cliente ya tiene el maximo de cuentas");
        }
    }//GEN-LAST:event_btcuentasActionPerformed

    private void btbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbuscarActionPerformed
DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Cuenta");
        
        int opcion = cuadroclientes.getSelectedRow();
        int temp =0;
        
        if (opcion>=0) {
           while (temp<maxcuentas) {
            System.out.println("Opcion: "+opcion);
            System.out.println("Opcion: "+temp);
            if (tablacuentas[opcion][temp]>0) {
                System.out.println("Cuenta: "+tablacuentas[opcion][temp]);
                model.addRow(new Object[]{tablacuentas[opcion][temp]});
                temp=temp+1;
            }
            else {
                temp=maxcuentas;
            }
           } 
           cuadrocuentas.setModel(model); 
        }
        else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente");    
        }
        
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("cui");
//        model.addColumn("nombre");
//        model.addColumn("apellido");
//        
//        if (contclientes>=0)   {
//            for(int temp=0; temp<=contclientes; temp++) {
//                model.addRow(new Object[]{tablaclientes[temp][0],tablaclientes[temp][1],tablaclientes[temp][2]});  
//            }  
//        }
//        
//        cuadroclientes.setModel(model); 
   
                                    
    }//GEN-LAST:event_btbuscarActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        double monto = 0;
        double saldo = 0;
        int origen = cborigen.getSelectedIndex();
        int destino = cbdestino.getSelectedIndex();

        if (origen>=0 && destino>0) {
            monto=Double.parseDouble(txtransferencias.getText());
            if (monto>0) {
                if (tablasaldos[origen]>=monto) {
                    
                    conttransacciones=conttransacciones+1;
                
                    Date date = Calendar.getInstance().getTime();
                    DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");
                    String strDate=dateFormat.format(date);
                    tabltransaccioness[conttransacciones][0]=strDate;
                
                    tabltransaccioness[conttransacciones][1]="Transferencia";
                    System.out.println(origen+" - "+strDate+" - Transferencia - ");                
                
                    tablatransaccionesi[conttransacciones][0]=origen;
                    tablatransaccionesi[conttransacciones][1]=monto;
                    tablatransaccionesi[conttransacciones][2]=0;
                
                    tablasaldos[origen]=tablasaldos[origen]-monto;
                    tablatransaccionesi[conttransacciones][3]=tablasaldos[origen]; 
                    System.out.println(monto+"- 0 - "+tablasaldos[origen]);
                    
                    conttransacciones=conttransacciones+1;
                
                    tabltransaccioness[conttransacciones][0]=strDate;
                
                    tabltransaccioness[conttransacciones][1]="Transferencia";
                    System.out.println(origen+" - "+strDate+" - Transferencia - ");                
                
                    tablatransaccionesi[conttransacciones][0]=destino;
                    tablatransaccionesi[conttransacciones][1]=0;
                    tablatransaccionesi[conttransacciones][2]=monto;
                
                    tablasaldos[destino]=tablasaldos[destino]+monto;
                    tablatransaccionesi[conttransacciones][3]=tablasaldos[destino]; 
                    System.out.println("0 -"+monto+"- "+tablasaldos[destino]);
                    
                    JOptionPane.showMessageDialog(null, "Transferencia realizada exitosamente");
                }
                else {
                    JOptionPane.showMessageDialog(null, "La cuenta origen no tiene suficientes fondos");    
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero");
            }
      
        } 
        
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una cuenta origen y una destino");
        }



    }//GEN-LAST:event_jButton5ActionPerformed

    private void btreporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreporteActionPerformed
        // TODO add your handling code here
        DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("Fecha");
            model.addColumn("Detalle");
            model.addColumn("Debito");
            model.addColumn("Crédito");
            model.addColumn("Saldo");
        
        int cuenta=Integer.parseInt(repcuenta.getText());
        
        //double cuenta=Double.parseDouble(repcuenta.getText());
        if (cuenta>=1 && cuenta<=contcuentas) {
            int cliente=tablacuentasclientes[cuenta];
            repcui.setText(tablaclientes[cliente][0]);
            repnombre.setText(tablaclientes[cliente][1]);
            repapellido.setText(tablaclientes[cliente][2]);
            
            int temp=0;
            while (temp<=conttransacciones) {
                
                //System.out.println("Temp: "+temp+" - Cont: "+conttransacciones);                
                
                int contenido=(int)tablatransaccionesi[temp][0]+1;
                
                //System.out.println("COMPARA - cta "+cuenta+" - trans: "+contenido);
                
                if (cuenta==contenido) {
                    
                    //System.out.println("IGUALES - cta "+cuenta+" - trans: "+contenido);
                    
                    model.addRow(new Object[]{
                        temp+1,
                        tabltransaccioness[temp][0],
                        tabltransaccioness[temp][1],        
                        tablatransaccionesi[temp][1],
                        tablatransaccionesi[temp][2],
                        tablatransaccionesi[temp][3]
                    });

                }    
                temp=temp+1; 
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Ingrese un número de cuenta válido");
        }
        repcuadro.setModel(model); 
    }//GEN-LAST:event_btreporteActionPerformed

    private void tfcuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcuiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcuiActionPerformed

    private void cbclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbclienteActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void cuadroclientesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cuadroclientesFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cuadroclientesFocusGained

    private void btdepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdepositosActionPerformed
        // TODO add your handling code here:
        double monto = 0;
        double saldo = 0;
        int opcion = cbdepositos.getSelectedIndex();
        if (opcion>=0) {
            monto=Double.parseDouble(txdepositos.getText());
            if (monto>0) {
                
                conttransacciones=conttransacciones+1;
                
                Date date = Calendar.getInstance().getTime();
                DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");
                String strDate=dateFormat.format(date);
                tabltransaccioness[conttransacciones][0]=strDate;
                tabltransaccioness[conttransacciones][1]="Deposito";
                System.out.println("Cuenta: "+opcion+" - Transacción: "+conttransacciones+" - Fecha: "+tabltransaccioness[conttransacciones][0]+" - Tipo: "+tabltransaccioness[conttransacciones][0]);                
                
                tablatransaccionesi[conttransacciones][0]=opcion;
                tablatransaccionesi[conttransacciones][1]=0;
                tablatransaccionesi[conttransacciones][2]=monto;
                
                tablasaldos[opcion]=tablasaldos[opcion]+monto;
                tablatransaccionesi[conttransacciones][3]=tablasaldos[opcion]; 
                System.out.println("Cuenta: "+tablatransaccionesi[conttransacciones][0]+" - Debe: "+tablatransaccionesi[conttransacciones][1]+" - Haber: "+tablatransaccionesi[conttransacciones][2]+" - Saldo: "+tablatransaccionesi[conttransacciones][3]);                
                
                JOptionPane.showMessageDialog(null, "Deposito realizado exitosamente");
            }
            else {
                JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero");
            }
      
        } 
        
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una cuenta");
        }
       
     

        
    }//GEN-LAST:event_btdepositosActionPerformed

    private void cbdepositosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdepositosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdepositosActionPerformed

    private void btserviciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btserviciosActionPerformed
        // TODO add your handling code here:
        double monto = 0;
        double saldo = 0;
        int opcion = cbservicios.getSelectedIndex();
        int tipo = cbtipo.getSelectedIndex();
        String tipos = cbtipo.getSelectedItem().toString();
        if (opcion>=0 && tipo>0) {
            monto=Double.parseDouble(txservicios.getText());
            if (monto>0) {
                if (tablasaldos[opcion]>=monto) {
                    conttransacciones=conttransacciones+1;
                
                    Date date = Calendar.getInstance().getTime();
                    DateFormat dateFormat = new SimpleDateFormat("dd-mm-yyyy hh:mm:ss");
                    String strDate=dateFormat.format(date);
                    tabltransaccioness[conttransacciones][0]=strDate;
                
                    tabltransaccioness[conttransacciones][1]=tipos;
                    System.out.println("Cuenta: "+opcion+" - Transacción: "+conttransacciones+" - Fecha: "+tabltransaccioness[conttransacciones][0]+" - Tipo: "+tabltransaccioness[conttransacciones][0]);                
                               
                
                    tablatransaccionesi[conttransacciones][0]=opcion;
                    tablatransaccionesi[conttransacciones][1]=monto;
                    tablatransaccionesi[conttransacciones][2]=0;
                
                    tablasaldos[opcion]=tablasaldos[opcion]-monto;
                    tablatransaccionesi[conttransacciones][3]=tablasaldos[opcion]; 
                    System.out.println("Cuenta: "+tablatransaccionesi[conttransacciones][0]+" - Debe: "+tablatransaccionesi[conttransacciones][1]+" - Haber: "+tablatransaccionesi[conttransacciones][2]+" - Saldo: "+tablatransaccionesi[conttransacciones][3]);                
                
                    
                    JOptionPane.showMessageDialog(null, "Pago realizado exitosamente");
                }
                else {
                    JOptionPane.showMessageDialog(null, "La cuenta origen no tiene suficientes fondos");    
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "El monto debe ser mayor a cero");
            }
      
        } 
        
        else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una cuenta y un tipo de servicio");
        }
       
        
        
    }//GEN-LAST:event_btserviciosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cuenta().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbuscar;
    private javax.swing.JButton btcliente;
    private javax.swing.JTabbedPane btcuenta;
    private javax.swing.JButton btcuentas;
    private javax.swing.JButton btdepositos;
    private javax.swing.JButton btreporte;
    private javax.swing.JButton btservicios;
    private javax.swing.JComboBox<String> cbcliente;
    private javax.swing.JComboBox<String> cbdepositos;
    private javax.swing.JComboBox<String> cbdestino;
    private javax.swing.JComboBox<String> cborigen;
    private javax.swing.JComboBox<String> cbservicios;
    private javax.swing.JComboBox<String> cbtipo;
    private javax.swing.JTable cuadroclientes;
    private javax.swing.JTable cuadrocuentas;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField repapellido;
    private javax.swing.JTable repcuadro;
    private javax.swing.JTextField repcuenta;
    private javax.swing.JTextField repcui;
    private javax.swing.JTextField repnombre;
    private javax.swing.JTextField tfapellido;
    private javax.swing.JTextField tfcui;
    private javax.swing.JTextField tfnombre;
    private javax.swing.JTextField txdepositos;
    private javax.swing.JTextField txservicios;
    private javax.swing.JTextField txtransferencias;
    // End of variables declaration//GEN-END:variables
}
